[phases.setup] 
nixPkgs = ['dotnet-sdk_8'] 
 
[phases.build] 
cmds = ['dotnet publish -c Release -o out --self-contained true --runtime linux-x64 /p:PublishSingleFile=false'] 
 
[start] 
cmd = './out/RentACarReport' 
